#!/bin/sh

STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \.php`
BAD_PHP_WORDS="^\s*(var_dump|dump).*\\(.*\\)|<<<<<<<<\W|>>>>>>>>\W|========\W$"
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "\e[33m \e[1m"
echo "\n-- Checking bad PHP words: var_dump, dump, ..."
echo "\e[0m"
for FILE in $SFILES
do
    grep -H -i -n -E "${BAD_PHP_WORDS}" $FILE
    if [ $? -eq 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $FILE"
done
echo "No bad PHP words detected"


# Check Code Sniffer
if [ "$FILES" != "" ]
then
    echo "\e[33m \e[1m"
    echo "\n-- Running Code Sniffer for PSR12 standard"
    echo "\e[0m"
    php ./vendor/bin/phpcs -s --standard=PSR12 -n -p $FILES

    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        exit 1
    fi
fi

# Check Unit Tests
if [ "$FILES" != "" ]
then
    echo "Running unit tests"
    make test
fi

exit $?
