parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    THN\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
    # THN\Shared\:
    #     resource: '../src/Shared/'
    THN\Apps\Backoffice\:
        resource: '../apps/backoffice/src/'
        tags: ['controller.service_arguments']
